/*
 * This Java source file was generated by the Gradle 'init' task.
 */
 import westland.signature.automator.*;
public class Library
{
    public static Table runMultiJoin()
    {
      Table collectionDetails = Initializer.getTable("./src/main/resources/collectionDetails.csv");
      Table collection = Initializer.getTable("./src/main/resources/collection.csv");
      Table contacts = Initializer.getTable("./src/main/resources/contacts.csv");
      Table journals = Initializer.getTable("./src/main/resources/journals.csv");
      Table journalAccounts = Initializer.getTable("./src/main/resources/journalAccounts.csv");

      return collectionDetails.leftJoin(collection).leftJoin(contacts).leftJoin(journals).leftJoin(journalAccounts);
    }
}
